---
title: "Automated Machine Learning with H2O(I)"
subtitle: "Business Decisions with Machine Learning"
author: "Drew Gilmore"
---

# Challenge Responses

1. Compensation Features

What can you deduce about the interaction between Monthly Income and Attrition?

**Answer: c) Those that are leaving have a lower Monthly Income**

2. Compensation Features

What can you deduce about the interaction between Percent Salary Hike and Attrition?

**Answer: c) Those that are leaving have lower Percent Salary Hike**
*I'm not sure if the difference is statistically significant*

3. Compensation Features

What can you deduce about the interaction between Stock Option Level and Attrition?

**Answer: b) Those that are staying have a higher stock option level**


4. Survey Results

What can you deduce about the interaction between Environment Satisfaction and Attrition?

**Answer: c) It's difficult to deduce anything based on the visualization**

5. Survey Results

What can you deduce about the interaction between Work Life Balance and Attrition

**Answer: b) Those that are staying have a higher density of 2's and 3's**

6. Performance Data

What Can you deduce about the interaction between Job Involvement and Attrition?

**Answer: a) Those that are leaving have a lower density of 3's and 4's**

7. Work-Life Features

What can you deduce about the interaction between Over Time and Attrition?

**Answer: a) The proportion of those leaving that are working Over Time are high compared to those that are not leaving**

8. Training and Education

What can you deduce about the interaction between Training Times Last Year and Attrition

**Answer: b) People that leave tend to have less annual trainings**

9. Time-Based Features

What can you deduce about the interaction between Years At Company and Attrition

**Answer: b) People that leave tend to have less working years at the company**

10. Time-Based Features

What can you deduce about the interaction between Years Since Last Promotion and Attrition?

**Answer: c) It's difficult to deduce anything based on the visualization**

# Script

```{r, echo = T , warning=FALSE, error=FALSE, message=FALSE}
library(tidyverse)
library(GGally)

employee_attrition_tbl <- read_csv("Challenge 3/datasets-1067-1925-WA_Fn-UseC_-HR-Employee-Attrition.csv")


data <- employee_attrition_tbl %>%
  select(Attrition, Age, Gender, MaritalStatus, NumCompaniesWorked, Over18, DistanceFromHome)

plot_ggpairs <- function(data, color = NULL, density_alpha = 0.5) {
  
  color_expr <- enquo(color)
  
  if (rlang::quo_is_null(color_expr)) {
    
    g <- data %>%
      ggpairs(lower = "blank") 
    
  } else {
    
    color_name <- quo_name(color_expr)
    
    g <- data %>%
      ggpairs(mapping = aes_string(color = color_name), 
              lower = "blank", legend = 1,
              diag = list(continuous = wrap("densityDiag", 
                                            alpha = density_alpha))) +
      theme(legend.position = "bottom")
  }
  
  return(g)
  
}

#   1. Descriptive features: age, gender, marital status 
employee_attrition_tbl %>%
  select(Attrition, Age, Gender, MaritalStatus, NumCompaniesWorked, Over18, DistanceFromHome) %>%
  plot_ggpairs(Attrition)

#   2. Employment features: department, job role, job level
employee_attrition_tbl %>%
  select(Attrition, contains("employee"), contains("department"), contains("job")) %>%
  plot_ggpairs(Attrition) 

#   3. Compensation features: HourlyRate, MonthlyIncome, StockOptionLevel 
employee_attrition_tbl %>%
  select(Attrition, contains("income"), contains("rate"), contains("salary"), contains("stock")) %>%
  plot_ggpairs(Attrition)

#   4. Survey Results: Satisfaction level, WorkLifeBalance 
employee_attrition_tbl %>%
  select(Attrition, contains("satisfaction"), contains("life")) %>%
  plot_ggpairs(Attrition)

#   5. Performance Data: Job Involvment, Performance Rating
employee_attrition_tbl %>%
  select(Attrition, contains("performance"), contains("involvement")) %>%
  plot_ggpairs(Attrition)

#   6. Work-Life Features 
employee_attrition_tbl %>%
  select(Attrition, contains("overtime"), contains("travel")) %>%
  plot_ggpairs(Attrition)

#   7. Training and Education 
employee_attrition_tbl %>%
  select(Attrition, contains("training"), contains("education")) %>%
  plot_ggpairs(Attrition)

#   8. Time-Based Features: Years at company, years in current role
employee_attrition_tbl %>%
  select(Attrition, contains("years")) %>%
  plot_ggpairs(Attrition)
```

